ENGR00333251 dts: imx6dl: epdc: fix dtb build error
ERROR (phandle_references): Reference to non-existent node or label "reg_sensor"

ERROR: Input tree has errors, aborting (use -f to force output)
make[1]: *** [arch/arm/boot/dts/imx6dl-cubox-i.dtb] Error 2
make[1]: *** Waiting for unfinished jobs....
  DTC     arch/arm/boot/dts/imx6dl-sabresd-enetirq.dtb
...

The label "reg_sensor" is defined in imx6qdl-sabresd.dts, not in
imx6dl.dtsi. The patch moves the epdc parts to imx6dl-sabresd.dts,
which also sounds better since EPDC module is available not on i.mx6q
but i.mx6dl.

Signed-off-by: Robby Cai <r63905@freescale.com>